### ISSUE TITLE
Issue with 140 characters plus

### ISSUE THREAD

**Issue by theDraco** [kav2k/silver_feather#38]
Twitter has recently made it so when you attach an image or quote another tweet it doesn't take away from your 140 character count. This means you can type 140 characters plus quote another tweet or attach an image. 

On tweets that do this, they get cut off in the Silver Feather window and it leaves a link that you have to click on to go to Twitter's website and see the whole tweet. Can someone please fix this?

**Comment by kav2k** [comment]
I have a partial fix for this, but it still has a bug that needs to be resolved before I roll it out.

In general though, I will admit I'm not very good at maintaining this - it's a very low priority for me.

**Comment by kav2k** [comment]
Closed with 243ecfec315e8be0974bc405df5ce93cdd3131d0

There are still lingering bugs I'm gonna file now.
